sonar.projectKey=LRM_Client
sonar.organization=ansforge
sonar.sources=.
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=cypress/**,cypress.config.js,Dockerfile,tsconfig.json
