plugins {
    id 'java'
    // The following line allows to load io.gatling.gradle plugin and directly apply it
    id 'io.gatling.gradle' version '3.11.3'
    id 'com.google.cloud.tools.jib' version '3.4.4'
}

dependencies {
    gatling("org.galaxio:gatling-amqp-plugin_2.13:0.14.0")
    gatling("io.github.cdimascio:dotenv-java:3.2.0")
}

gatling {
  enterprise {
    // Enterprise Cloud (https://cloud.gatling.io/) configuration reference: https://gatling.io/docs/gatling/reference/current/extensions/gradle_plugin/#working-with-gatling-enterprise-cloud
    // Enterprise Self-Hosted configuration reference: https://gatling.io/docs/gatling/reference/current/extensions/gradle_plugin/#working-with-gatling-enterprise-self-hosted
  }
}

repositories {
  mavenCentral()
}

jib {
    from {
        image = 'eclipse-temurin:21-jre'
    }
    to {
        image = project.findProperty('image') ?: 'ghcr.io/ansforge/tmc:latest'
        tags = [project.findProperty('version') ?: 'latest']
    }
    container {
        mainClass = 'io.gatling.app.Gatling'
        jvmFlags = ['-Xms512m', '-Xmx2048m']
        environment = [:]
        ports = []
    }
}
