apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-rabbitmq-rules
  labels:
    release: prometheus-operator
spec:
  groups:
    - name: rabbitmq.rules
      rules:
        - alert: DispatcherLatency
          expr: rabbitmq_queue_messages{queue="dispatch"} > 3
          for: 30s # wait 30s before firing the alert -> if the condition isn't still true, the alert won't be fired
          labels:
            latency: "dispatcher" # custom key/value pair to be used in the alertmanager config
          annotations:
            summary: "Latency on the dispatcher queue"
            description: "There are more than 3 messages available in the dispatch queue"
            # it is possible to template the description with certain variables.
            # See https://prometheus.io/docs/alerting/latest/notifications/#templating
            # So we should be able to display the queue name, and pass it to the alertmanager
            # then resolve the email recipient based on the queue name ?