sonar.projectKey=ansforge_SAMU-Hub-Sante
sonar.organization=ansforge
sonar.sources=./hub/dispatcher/src/main,./web/lrm/client,./web/lrm/server,./tools/healthcheck
sonar.java.binaries=./hub/dispatcher/build/classes