spring:
  rabbitmq:
    ssl:
      enabled: true
      key-store-password: password
      trust-store-password: password
      key-store: "file:<PATH_TO_LOCAL_DEV_DIRECTORY>/config/certs/dispatcher.p12"
      trust-store: "file:<PATH_TO_LOCAL_DEV_DIRECTORY>/config/certs/trustStore"
client:
  configuration:
    file: "file:<PATH_TO_LOCAL_DEV_DIRECTORY>/config/values/clients.yaml"
supported:
  messages:
    file: "file:<PATH_TO_LOCAL_DEV_DIRECTORY>/dispatcher/supported.messages.csv"
