spring:
  rabbitmq:
    host: localhost
    port: 5671
    publisher-returns: true
    template:
      mandatory: true
logging:
  level:
    com.hubsante.hub: DEBUG
conversion:
  service:
    url: http://localhost:8083
