spring:
  rabbitmq:
    ssl:
      enabled: true
      key-store-password: password
      trust-store-password: password
      key-store: "file:<PATH_TO_LOCAL_DEV_DIRECTORY>/config/certs/dispatcher.p12"
      trust-store: "file:<PATH_TO_LOCAL_DEV_DIRECTORY>/config/certs/trustStore"
  main:
    web-application-type: reactive
client:
  preferences:
    file: "file:<PATH_TO_LOCAL_DEV_DIRECTORY>/config/values/client.preferences.csv"
supported:
  messages:
    file: "file:<PATH_TO_LOCAL_DEV_DIRECTORY>/dispatcher/supported.messages.csv"
