declare global {
  interface Window {
    __ENV__?: {
      VITE_SPECS_API_DOMAIN?: string;
      VITE_SPECS_PUBLIC_VERSIONS?: string[];
    };
  }
}

// env-config.js is generated by docker-entrypoint.sh at container
// start (nginx serves static files, can't bake env vars at runtime). Falls
// back to Vite's build-time env for local dev (`pnpm dev`).
export const apiDomain =
  window.__ENV__?.VITE_SPECS_API_DOMAIN ||
  import.meta.env.VITE_SPECS_API_DOMAIN;

// refs visible when logged out, newest first; numeric sort puts 3.5.0-rc.1
// after 3.5.0, fine until a prerelease and its release are both listed
export const publicVersions: string[] = [
  ...(window.__ENV__?.VITE_SPECS_PUBLIC_VERSIONS ??
    JSON.parse(import.meta.env.VITE_SPECS_PUBLIC_VERSIONS ?? "[]")),
].sort((a, b) => b.localeCompare(a, undefined, { numeric: true }));

export const defaultRef = "main";
// no public version configured: fall back to main rather than redirect forever
export const defaultPublicVersion: string = publicVersions[0] ?? defaultRef;

export const resolveDefaultRef = (isAuthenticated: boolean) =>
  isAuthenticated ? defaultRef : defaultPublicVersion;

export const rawGithubDomain = "raw.githubusercontent.com";
export const githubDomain = "github.com";
export const githubRepo = "ansforge/SAMU-Hub-Modeles";

export function buildGithubUrl(
  domain: string,
  ref: string,
  path: string,
): string {
  return `https://${domain}/${githubRepo}/${ref}/${path}`;
}

export function messageListUrl(ref: string): string {
  return buildGithubUrl(
    rawGithubDomain,
    ref,
    "src/main/resources/sample/examples/messagesList.json",
  );
}

export const NOMENCLATURE_KEY = "x-nomenclature";
