declare global {
  interface Window {
    __ENV__?: { VITE_SPECS_API_DOMAIN?: string };
  }
}

// env-config.js is generated by docker-entrypoint.sh at container
// start (nginx serves static files, can't bake env vars at runtime). Falls
// back to Vite's build-time env for local dev (`pnpm dev`).
export const apiDomain =
  window.__ENV__?.VITE_SPECS_API_DOMAIN ||
  import.meta.env.VITE_SPECS_API_DOMAIN;



export const defaultRef = "main";

export function messageListUrl(ref: string): string {
  return `https://raw.githubusercontent.com/ansforge/SAMU-Hub-Modeles/${ref}/src/main/resources/sample/examples/messagesList.json`;
}
