declare global {
  interface Window {
    __ENV__?: { VITE_SPECS_API_DOMAIN?: string };
  }
}

export const repo = "ansforge/SAMU-Hub-Modeles";
// env-config.js is generated by docker-entrypoint.sh at container
// start (nginx serves static files, can't bake env vars at runtime). Falls
// back to Vite's build-time env for local dev (`pnpm dev`).
export const apiDomain =
  window.__ENV__?.VITE_SPECS_API_DOMAIN ||
  import.meta.env.VITE_SPECS_API_DOMAIN;

export const defaultRef = "main";
export const schemaPath = "src/main/resources/json-schema";
export const defaultWorkingBranch = "specs/working-poc";

// pass as a Link's `search` prop to carry the current ref along when
// navigating, defaulting it if absent
export function preserveRefSearch(prev: { ref?: string }): { ref: string } {
  return { ref: prev.ref ?? defaultRef };
}

export function messageListUrl(ref: string): string {
  return `https://raw.githubusercontent.com/${repo}/${ref}/src/main/resources/sample/examples/messagesList.json`;
}

export const NOMENCLATURE_KEY = "x-nomenclature";
