{{ $clusterNamespace := .Values.clusterNamespace }}
{{- range .Values.clients }}
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: {{ .client_id | lower }}-permission
  namespace: {{ $clusterNamespace }}
spec:
  vhost: "/"
  user: {{ .common_name }} # name of the RabbitMQ user
  permissions:
    write:  "hubsante"
    configure: ""
{{ if .additional_permissions }}
    read: {{ printf "^(fr.health.%s.*" .client_id }} {{ range .additional_permissions }}{{ printf "|fr.health.%s.*" . }} {{ end }} {{ printf ")" }}
{{ else }}
    read: {{ printf "^fr.health.%s.*" .client_id }}
{{ end }}
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: {{ $clusterNamespace }}
---
{{- end }}