# templates/client-users.yaml
{{ $clusterNamespace := .Values.clusterNamespace }}
{{- range .Values.clients }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-{{ .client_id | lower }}-secret
  namespace: {{ $clusterNamespace }}
type: Opaque
stringData:
  username: '{{ .common_name }}'
  password: ''
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: {{ .client_id | lower }}-user
  namespace: {{ $clusterNamespace }}
spec:
  importCredentialsSecret:
    name: rabbitmq-{{ .client_id | lower }}-secret
  tags: []
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: {{ $clusterNamespace }}
---
  {{- end }}