{{ $clusterNamespace := .Values.clusterNamespace }}
{{- range .Values.clients }}
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: {{ .client_id | lower }}.message-queue-binding
  namespace: {{ $clusterNamespace }}
spec:
  source: distribution
  destination: fr.health. {{ .client_id }}.message
  destinationType: queue
  routingKey: fr.health.{{ .client_id }}.message
  vhost: "/"
  rabbitmqClusterReference:
    namespace: {{ $clusterNamespace }}
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: {{ .client_id | lower }}.ack-queue-binding
  namespace: {{ $clusterNamespace }}
spec:
  source: distribution
  destination: fr.health.{{ .client_id }}.ack
  destinationType: queue
  routingKey: fr.health.{{ .client_id }}.ack
  vhost: "/"
  rabbitmqClusterReference:
    namespace: {{ $clusterNamespace }}
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: {{ .client_id | lower }}.info-queue-binding
  namespace: {{ $clusterNamespace }}
spec:
  source: distribution
  destination: fr.health.{{ .client_id }}.info
  destinationType: queue
  routingKey: fr.health.{{ .client_id }}.info
  vhost: "/"
  rabbitmqClusterReference:
    namespace: {{ $clusterNamespace }}
    name: rabbitmq
---
    {{- end }}