apiVersion: rabbitmq.com/v1beta1
kind: Policy
metadata:
  name: dead-lettering-policy # name of this custom resource
  namespace: {{ .Values.clusterNamespace }}
spec:
  name: dead-lettering
  pattern: "^.*\\.(?:ack|info|message)$" # double the escape character because the template will be rendered first byt gotpl
  applyTo: "queues"
  definition:
    message-ttl: 10000
    dead-letter-exchange: distribution.dlx
  priority: 0
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: {{ .Values.clusterNamespace }}