{{ if .Values.test_lrm.enabled}}
{{ $clusterNamespace := .Values.clusterNamespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-local-user-secret
  namespace: {{ $clusterNamespace }}
type: Opaque
stringData:
  username: 'local.test'
  password: ''
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: local-user
  namespace: {{ $clusterNamespace }}
spec:
  importCredentialsSecret:
    name: rabbitmq-local-user-secret
  tags: []
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: {{ $clusterNamespace }}
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: local-user-permission
  namespace: {{ $clusterNamespace }}
spec:
  vhost: "/"
  userReference:
    name: local-user # name of the user resource (not the username)
  permissions:
    write:  hubsante
    configure: ""
    read: |
      "^(fr.health.samuA.*|fr.health.samuB.*|fr.health.samuC.*|fr.fire.nexsis.sdisZ.*|
      fr.health.test.bisom.*|fr.health.test.scriptal.*|fr.health.test.appligos.*|
      fr.health.test.exos.*|fr.health.test.inetum.*|fr.health.test.rramu.*)$"
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: {{ $clusterNamespace }}
---
apiVersion: rabbitmq.com/v1beta1
kind: TopicPermission
metadata:
  name: local-user-topic-permission
  namespace: {{ $clusterNamespace }}
spec:
  vhost: "/"
  userReference:
    name: local-user # name of the user resource (not the username)
  permissions:
    exchange: "hubsante"
    write:  |
      "^(fr.health.samuA|fr.health.samuB|fr.health.samuC|fr.fire.nexsis.sdisZ|
      fr.health.test.bisom|fr.health.test.scriptal|fr.health.test.appligos|
      fr.health.test.exos|fr.health.test.inetum|fr.health.test.rramu)$"
    read: ""
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: {{ $clusterNamespace }}
---
{{ range .Values.editors }}
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: {{ .client_id | lower }}.test.message-queue
  namespace: {{ $clusterNamespace }}
spec:
  name: fr.health.test.{{ .client_id }}.message
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    namespace: {{ $clusterNamespace }}
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: {{ .client_id | lower }}.test.ack-queue
  namespace: {{ $clusterNamespace }}
spec:
  name: fr.health.test.{{ .client_id }}.ack
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    namespace: {{ $clusterNamespace }}
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: {{ .client_id | lower }}.test.info-queue
  namespace: {{ $clusterNamespace }}
spec:
  name: fr.health.test.{{ .client_id }}.info
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    namespace: {{ $clusterNamespace }}
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: {{ .client_id | lower }}.test.message-queue-binding
  namespace: {{ $clusterNamespace }}
spec:
  source: distribution
  destination: fr.health.test.{{ .client_id }}.message
  destinationType: queue
  routingKey: fr.health.test.{{ .client_id }}.message
  vhost: "/"
  rabbitmqClusterReference:
    namespace: {{ $clusterNamespace }}
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: {{ .client_id | lower }}.test.ack-queue-binding
  namespace: {{ $clusterNamespace }}
spec:
  source: distribution
  destination: fr.health.test.{{ .client_id }}.ack
  destinationType: queue
  routingKey: fr.health.test.{{ .client_id }}.ack
  vhost: "/"
  rabbitmqClusterReference:
    namespace: {{ $clusterNamespace }}
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: {{ .client_id | lower }}.test.info-queue-binding
  namespace: {{ $clusterNamespace }}
spec:
  source: distribution
  destination: fr.health.test.{{ .client_id }}.info
  destinationType: queue
  routingKey: fr.health.test.{{ .client_id }}.info
  vhost: "/"
  rabbitmqClusterReference:
    namespace: {{ $clusterNamespace }}
    name: rabbitmq
---
{{ end }}
{{ end}}
