[versions]
gatlingPlugin = "3.11.3"
jibPlugin = "3.5.1"
models = "3.4.1"
gatlingAmqpPlugin = "1.2.10"
dotenvJava = "3.2.0"
commonsIo = "2.15.1"
sshd = "2.12.1"

[plugins]
gatling = { id = "io.gatling.gradle", version.ref = "gatlingPlugin" }
jib = { id = "com.google.cloud.tools.jib", version.ref = "jibPlugin" }
