[versions]
springBoot = "4.1.0"
testcontainers = "1.21.4"
jsonSchemaValidator = "1.5.9"
logstashEncoder = "9.0"
univocityParsers = "2.9.1"
groovyJson = "3.0.25"
orgJson = "20231013"
googleJavaFormat = "1.29.0"
embedMongo = "4.33.0"
apacheCommonsCsv = "1.14.1"
tomcat = "11.0.22"
netty = "4.2.13.Final"
jacksonBom = "3.1.1"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }