[versions]
springBoot = "4.1.1"
testcontainers = "2.0.5"
logstashEncoder = "9.0"
univocityParsers = "2.9.1"
groovyJson = "3.0.25"
orgJson = "20231013"
googleJavaFormat = "1.36.1"
embedMongo = "4.33.0"
apacheCommonsCsv = "1.14.1"
tomcat = "11.0.26"
netty = "4.2.18.Final"
jacksonBom = "3.1.1"

[libraries]
tomcat-embed-core = { module = "org.apache.tomcat.embed:tomcat-embed-core", version.ref = "tomcat" }
netty-bom = { module = "io.netty:netty-bom", version.ref = "netty" }
jackson-bom = { module = "com.fasterxml.jackson:jackson-bom", version.ref = "jacksonBom" }
google-java-format = { module = "com.google.googlejavaformat:google-java-format", version.ref = "googleJavaFormat" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }