apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    namespace: default
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - hub.esante.gouv.fr
    secretName: landing-cert
  rules:
    - host: "hub.esante.gouv.fr"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world
                port:
                  number: 80
