services:
  rabbitmq:
    image: ${RABBIT_MQ_IMAGE:-rabbitmq:4.0.2}
    ports:
      - "5671:5671"
      - "15672:15672"
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - ../../hub/dispatcher/src/test/resources/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ../../hub/dispatcher/src/test/resources/config/certs/rabbitmq/ca.crt:/etc/rabbitmq-tls/ca.crt
      - ../../hub/dispatcher/src/test/resources/config/certs/rabbitmq/rabbitmq.crt:/etc/rabbitmq-tls/rabbitmq.crt
      - ../../hub/dispatcher/src/test/resources/config/certs/rabbitmq/rabbitmq.key:/etc/rabbitmq-tls/rabbitmq.key
      - ../../hub/dispatcher/src/test/resources/config/definitions.json:/config/definitions.json

  converter:
    image: ${CONVERTER_IMAGE}
    ports:
      - "8083:8080"

  dispatcher-1:
    image: ${DISPATCHER_1_IMAGE}
    environment:
      - V_HOST=${DISPATCHER_1_VHOST}
      - DISPATCHER_KEYSTORE_FILE=${DISPATCHER_KEYSTORE_FILE}
      - DISPATCHER_KEYSTORE_PASSWORD=${DISPATCHER_KEYSTORE_PASSWORD}
      - DISPATCHER_TRUSTSTORE_FILE=${DISPATCHER_TRUSTSTORE_FILE}
      - DISPATCHER_TRUSTSTORE_PASSWORD=${DISPATCHER_TRUSTSTORE_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./dispatcher/application.properties.yaml:/config/application.yaml
      - ./dispatcher/certs/:/certs/
      - ./dispatcher/client.preferences.csv:/config/client.preferences.csv
      - ./dispatcher/supported.messages.csv:/config/supported.messages.csv

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."
