plugins {
    id 'java'
    alias(libs.plugins.spring.boot)
    id 'io.spring.dependency-management' version '1.1.0'
    id 'com.google.cloud.tools.jib' version '3.4.0'
    id 'jacoco'
    id 'com.github.hierynomus.license' version '0.16.1'
    id 'com.diffplug.spotless' version '8.1.0'
}

group = 'com.hubsante'

ext {
    modelVersion = project.hasProperty('modelVersion') ? project.getProperty('modelVersion') : '3.1'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    /*
    * We use mavenCentral() for every dependency but the models library, which is published on GitHub Packages.
    * So we add a additional maven repository to fetch it
    *
    * During development, it can be convenient to be able to test changes in the models lib without having to publish it
    * In this case, we should execute the gradle task publishToMavenLocal() in the models project and then uncomment
    * the mavenLocal() line below. It will push the models lib to the local .m2 folder, and the gradle build on this project
    * will fetch it from there
     */
//    mavenLocal()
    mavenCentral()
    maven {
        url = uri("https://maven.pkg.github.com/ansforge/SAMU-Hub-Modeles")
        credentials {
            username = System.getenv('GITHUB_ACTOR')
            password = System.getenv('GITHUB_TOKEN')
        }
    }
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:${libs.versions.springBoot.get()}"
        mavenBom "org.testcontainers:testcontainers-bom:${libs.versions.testcontainers.get()}"
    }
}

dependencies {
    // ===== Modèle =====
    implementation "com.hubsante:models:${project.ext.modelVersion}"

    // ===== Spring Boot =====
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-aop'
    implementation 'org.springframework.boot:spring-boot-starter-amqp'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // ===== MongoDB =====
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'

    // ===== Observabilité =====
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'

    // ===== JSON / XML / CSV =====
    implementation "com.fasterxml.jackson.dataformat:jackson-dataformat-xml"
    implementation "com.networknt:json-schema-validator:${libs.versions.jsonSchemaValidator.get()}"
    implementation "net.logstash.logback:logstash-logback-encoder:${libs.versions.logstashEncoder.get()}"
    implementation "com.univocity:univocity-parsers:${libs.versions.univocityParsers.get()}"
    implementation "org.codehaus.groovy:groovy-json:${libs.versions.groovyJson.get()}"
    implementation "org.json:json:${libs.versions.orgJson.get()}"

    // ===== Lombok =====
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    // ===== Tests =====
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.amqp:spring-rabbit-test'

    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:rabbitmq'

}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

springBoot {
    mainClass = 'com.hubsante.hub.HubApplication'
}

allprojects {
    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
    }
}

apply from: 'gradle/tests.gradle'
apply from: 'gradle/license.gradle'
apply from: 'gradle/spotless.gradle'
apply from: 'gradle/jib.gradle'