#name: ✅ Code Coverage
#
#on: pull_request
#
#jobs:
#  code-coverage:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#
#      - name: Run Coverage
#        run: |
#          cd hub/dispatcher
#          chmod +x gradlew
#          # ToDo: Update so that tests are run as otherwise the task is skipped
#          ./gradlew jacocoTestReport
#
#      - name: Add coverage to PR
#        id: jacoco
#        uses: madrapps/jacoco-report@v1.3
#        with:
#          paths: ${{ github.workspace }}/hub/dispatcher/build/reports/jacoco/test/jacocoTestReport.xml
#          token: ${{ secrets.GITHUB_TOKEN }}
#          min-coverage-overall: 40
#          min-coverage-changed-files: 60
