name: Build dispatcher image
on:
  workflow_dispatch:
  push:
    tags:
      - 'dispatcher-*'
jobs:
  get-tags:
    runs-on: ubuntu-latest
    outputs:
      dispatcher-version: ${{ steps.extract-dispatcher-version.outputs.version }}
    steps:
      - name: Extract version from tag
        id: extract-dispatcher-version
        run: |
          TAG_NAME=${{ github.ref_name }}
          VERSION=${TAG_NAME#dispatcher-}
          PATTERN="^([0-9]+\.[0-9]+(\.[0-9]+)?)(-[A-Za-z0-9\.]+)*$"
          if [[ ! "$VERSION" =~ $PATTERN ]]; then
            echo "Invalid version number"
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build-dispatcher:
    name: Build Dispatcher images
    needs: get-tags
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hub/dispatcher

    strategy:
      matrix:
        model_version: ["1.2", "2.3", "3.1.1", "3.2.0-rc.3"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests, build and push Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISPATCHER_VERSION: ${{ needs.get-tags.outputs.dispatcher-version }}
          MODEL_VERSION: ${{ matrix.model_version }}
        run: |
          IMAGE_TAG="${DISPATCHER_VERSION}-model-${MODEL_VERSION}"
            echo "Building image for $IMAGE_TAG"
          ./gradlew jib \
            -Pversion=$DISPATCHER_VERSION \
            -PmodelVersion=$MODEL_VERSION \
            --image ghcr.io/${{ github.repository_owner }}/dispatcher:$IMAGE_TAG
