name: Healthcheck CI

on:
  push:
    branches:
      - main
    paths:
      - "tools/healthcheck/**"

  pull_request:
    branches:
      - "**"
    paths:
      - "tools/healthcheck/**"

jobs:
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tools/healthcheck

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "3.11"

      - name: Install dependencies
        run: uv sync

      - name: Check formatting
        run: uv run ruff format --check .

      - name: Check linting
        run: uv run ruff check .

      - name: Run tests & generate HTML coverage report
        # TODO: try to mock the env variables in the tests directly
        env:
          RABBITMQ_URL: "foo"
          RABBITMQ_MONITORING_USERNAME: "foo"
          RABBITMQ_MONITORING_PASSWORD: "bar"
          DISPATCHER_INSTANCES: "bar"
        run: |
          uv run coverage run -m unittest tests/*.py
          uv run coverage report -m
          uv run coverage html

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          # Working directory is not used in the action
          # https://github.com/actions/upload-artifact/issues/232
          path: tools/healthcheck/htmlcov
          retention-days: 7

  security-scan:
    uses: ./.github/workflows/security-scan.yml
    with:
      working-directory: 'tools/healthcheck'
      project-type: 'python'
      python-version: '3.11'
      component-name: 'healthcheck'
      scan-dockerfile: true
      dependency-scan: true
