name: LRM Client CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'web/lrm/client/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'web/lrm/client/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web/lrm/client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Run ESLint
        run: yarn lint:js

      - name: Run Stylelint
        run: yarn lint:css

      - name: Run Prettier check
        run: npx prettier --check "**/*.{js,ts,vue,css,scss}"

  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web/lrm/client
    env:
      NUXT_PUBLIC_VHOST_MAP: |
        {
          "15-15_v1.5": "1.0",
          "15-nexsis_v1.8": "1.0",
          "15-smur_v1.4": "1.0",
          "15-gps_v1.0": "1.0"
        }
      NUXT_PUBLIC_CLIENT_MAP: |
        [
          ["fr.health.samuA",["fr.health.samuC"]],
          ["fr.health.samuC",["fr.health.samuA"]]
        ]
      NUXT_PUBLIC_MODEL_BRANCH: develop
      NUXT_PUBLIC_BACKEND_LRM_SERVER: integration.hub.esante.gouv.fr

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install required system packages
        run: sudo apt-get update && sudo apt-get install -y build-essential python3

      - name: Clean install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'http://localhost:3000/lrm'
          wait-on-timeout: 120
          working-directory: web/lrm/client
          build: yarn build:test
          start: yarn start
          browser: chrome

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: web/lrm/client/cypress/screenshots
          if-no-files-found: ignore