name: build image on release
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  extract-release-info:
    runs-on: ubuntu-latest
    outputs:
      project: ${{ steps.extract_info.outputs.project }}
      version: ${{ steps.extract_info.outputs.version }}
      matrix: ${{ steps.extract_info.outputs.matrix }}
    steps:
      - name: Extract release information
        id: extract_info
        run: |
          RELEASE_NAME=${{ github.event.release.name || github.ref_name }}
          echo $RELEASE_NAME
          
          if [[ "$RELEASE_NAME" == dispatcher-* ]]; then
            PROJECT="dispatcher"
            VERSION=${RELEASE_NAME#dispatcher-}
          elif [[ "$RELEASE_NAME" == lrm-* ]]; then
            PROJECT="lrm"
            VERSION=${RELEASE_NAME#lrm-}
          elif [[ "$RELEASE_NAME" == landing-* ]]; then
            PROJECT="landing"
            VERSION=${RELEASE_NAME#landing-}
          elif [[ "$RELEASE_NAME" == healthcheck-* ]]; then
            PROJECT="healthcheck"
            VERSION=${RELEASE_NAME#healthcheck-}
          elif [[ "$RELEASE_NAME" == chatbot-* ]]; then
            PROJECT="chatbot"
            VERSION=${RELEASE_NAME#chatbot-}
          elif [[ "$RELEASE_NAME" == specs-* ]]; then
            PROJECT="specs"
            VERSION=${RELEASE_NAME#specs-}
          elif [[ "$RELEASE_NAME" == openssl-* ]]; then
            PROJECT="openssl"
            VERSION=${RELEASE_NAME#openssl-}
          elif [[ "$RELEASE_NAME" == annuaire-* ]]; then
            PROJECT="annuaire"
            VERSION=${RELEASE_NAME#annuaire-}
          else
            echo "Invalid release name prefix. Must be 'dispatcher', 'lrm', 'landing', 'healthcheck', 'chatbot', 'specs' or 'annuaire'."
            exit 1
          fi
          
          PATTERN="^([0-9]+\.[0-9]+(\.[0-9]+)?)(-[A-Za-z0-9\.]+)*$"
          if [[ ! "$VERSION" =~ $PATTERN ]]; then
            echo "Invalid version number"
            exit 1
          fi
          
          echo "project=$PROJECT" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
          # Define matrix based on project
          case $PROJECT in
            lrm)
              MATRIX='{"include":[{"name":"lrm-backend","context":"./web/lrm/server","tag":"hub-lrm-back","artifact-name":"trivy-reports-lrm-backend"},{"name":"lrm-frontend","context":"./web/lrm/client","tag":"hub-lrm-front","artifact-name":"trivy-reports-lrm-frontend"}]}'
              ;;
            landing)
              MATRIX='{"include":[{"name":"landing","context":"./web/landing","tag":"hub-web-landing","artifact-name":"trivy-reports-landing"}]}'
              ;;
            healthcheck)
              MATRIX='{"include":[{"name":"healthcheck","context":"./tools/healthcheck","tag":"hub-healthcheck","artifact-name":"trivy-reports-healthcheck"}]}'
              ;;
            chatbot)
              MATRIX='{"include":[{"name":"chatbot","context":"./tools/chatbot","tag":"hub-chatbot","artifact-name":"trivy-reports-chatbot"}]}'
              ;;
            openssl)
              MATRIX='{"include":[{"name":"openssl","context":"./tools/openssl","tag":"openssl","artifact-name":"trivy-reports-openssl"}]}'
              ;;
            specs)
              MATRIX='{"include":[{"name":"specs","context":"./web/specs","tag":"hub-specs","artifact-name":"trivy-reports-specs"}]}'
              ;;
            annuaire)
              MATRIX='{"include":[{"name":"annuaire","context":"./tools/annuaire","tag":"hub-annuaire","artifact-name":"trivy-reports-annuaire"}]}'
              ;;
          esac
          
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  build-image:
    needs: extract-release-info
    if: needs.extract-release-info.outputs.project != 'dispatcher'
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.extract-release-info.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.tag }}:${{ needs.extract-release-info.outputs.version }}
          context: ${{ matrix.context }}

      - name: Scan Docker image
        continue-on-error: true
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/${{ matrix.tag }}:${{ needs.extract-release-info.outputs.version }}'
          format: 'sarif'
          output: 'trivy-${{ matrix.name }}-image.sarif'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'

      - name: Upload image scan results to GitHub Security tab
        if: always() && hashFiles('trivy-${{ matrix.name }}-image.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-${{ matrix.name }}-image.sarif'
          category: 'trivy-${{ matrix.name }}-image'

      - name: Upload image scan reports as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: '*.sarif'
          retention-days: 7
